### ISSUE TITLE
bower.json file for example?

### ISSUE THREAD

**Issue by AKST** [philopon/purescript-simple-assert#1]
It's not immediately obvious that there are additional dependencies to build the example (well at least, for me it wasn't), it might be worth while to include a bower.json file. Also that way other people don't have to guess the package names :P

**Comment by philopon** [comment]
Thanks for your feedback:smile:
devDependencies entry of bower.json is indicate it. so, these are installed when execute `bower install`.
Do you think It's insufficient?

**Comment by AKST** [comment]
Whoops, I must have missed that! Sorry about that

**Comment by philopon** [comment]
I don't mind it:smile:
